config/routes.rb
BootOverflow::Application.routes.draw do
  get 'sign_up'=> 'users#new', :as => 'sign_up'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  root :to => 'users#index'

  concern :commentable do
    resources :comments, only: [:index, :new, :create]
  end

  concern :votable do
    resources :votes, only: [:new, :create, :destroy]
  end

  resources :users, :only => [:index, :new, :create]

  resources :questions do
    concerns :commentable
    concerns :votable
    resources :answers, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :answers do
    concerns :commentable
    concerns :votable
  end

  resources :sessions, :only => [:new, :create, :destroy]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :content, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  validates :body, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :questions
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find params[:question_id]
    @answer = @question.answers.new
  end

  def create
    @question = Question.find params[:question_id]
    @answer = @question.answers.new answer_params
    if @answer.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find params[:question_id]
    @answer = @question.answers.find params[:id]
  end

  def update
    @question =Question.find params[:question_id]
    @answer = @question.answers.find params[:id]

    if @answer.update_attributes answer_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    question = Question.find params[:question_id]
    answer = question.answers.find params[:id]

    answer.destroy
    redirect_to question_path(question)
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_user!
    redirect_to new_session_path unless current_user.present?
  end

  def login user
    session[:user_id] = user.id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

   def new
    @comment = @commentable.comments.new
   end

  def create
    @comment = @commentable.comments.new comment_params
    if @comment.save
      if params[:question_id]
        question = Question.find params[:question_id]
        redirect_to question_path(question)
      else
        answer = Answer.find params[:answer_id]
        question = Question.find(Answer.find(params[:answer_id]).question_id)
        redirect_to question_path(question)
      end
    else
      render :new
    end
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    p resource
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :set_current_question, only: [:destroy, :edit, :update, :show]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end

  def create
    @user = User.find(current_user)
    @question = @user.questions.new(question_params)
    if current_user && @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def destroy
    if current_user
      @question.destroy
      redirect_to questions_path
    else
      redirect_to new_sessions_path
    end
  end

  def edit
  end

  def update
    if current_user && @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      redirect_to new_sessions_path
    end
  end

  private

  def set_current_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email params[:email]

    if @user && @user.authenticate(params[:password])
      login @user
      redirect_to users_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      @user = User.find(current_user)
      @questions = @user.questions

# Counting the number of answers and comments
      @answer = []
      @comments = []

      @questions.each do |question|
        @answer << question.answers.count
        @comments << question.comments.count
          question.answers.each do |answer|
            @comments << answer.comments.count
          end
      end
      render 'index'
    else
      redirect_to new_session_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save

      redirect_to root_path
    else
       p "errors #{@user.errors.full_messages}"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :cohort, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :load_votable

  def new
    @vote = @votable.votes.new
  end

  def create
    @vote = @votable.votes.new votes_params
    if params[:question_id]
      @question = Question.find(params[:question_id])
      if current_user && @vote.save
        render :partial => 'votes/votes_questions', :locals => {:question => @question}
      end
    else
      @answer = Answer.find(params[:answer_id])
      if current_user && @vote.save
        render :partial => 'votes/votes_answers', :locals => {:answer => @answer}
      end
    end
  end

  def destroy
    @vote = @votable.votes.find(votes_params)
    if params[:question_id]
      @question = Question.find(params[:question_id])
      if current_user
        @vote.destroy
        render :partial => 'votes/votes_questions', :locals => {:question => @question}
      end
    elsif params[:answer_id]
      @answer = Answer.find(params[:answer_id])
      if current_user
        @vote.destroy
        render :partial => 'votes/votes_answers', :locals => {:answer => @answer}
      end
    end
  end

  private

  def load_votable
    resource, id = request.path.split('/')[1, 2]
    p resource
    @votable = resource.singularize.classify.constantize.find(id)
  end

  def votes_params
    params.require(:vote).permit(:vote)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/edit.html.erb
<h1 class="page-header">Edit the Response</h1>

<%= form_for [@question, @answer] do |f| %>
 <%= f.text_area :content, placeholder: 'write your answer', rows: 25, cols: 47 %>
 <%= f.submit 'submit', id: 'submit' %>
<% end %>

app/views/answers/new.html.erb
<h1 class="page-header">Answer A Boot</h1>

<%= form_for [@question, @answer] do |f| %>
 <%= f.text_area :content, placeholder: 'write your answer' , rows: 25, cols: 47 %>
 <%= f.submit 'submit', id: 'submit' %>
<% end %>

app/views/comments/new.html.erb
<h1 class="page-header">Comment It</h1>

<%= form_for [@commentable, @comment] do |f| %>
  <%= f.text_area :body, placeholder: 'enter a comment', rows: 25, cols: 47 %>
  <%= f.submit 'submit' , id: 'submit' %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <%= link_to 'Profile', root_path %>
  <%= link_to 'Questions', questions_path %>
  <%= link_to 'Sign Out', session_path(current_user), :method => :delete, id: 'logout' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootOverflow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= render 'layouts/navbar' %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/questions/_answer_comments.html.erb
<% @question.answers.each do |answer| %>
  <div class="question-content">
    <div class="delete-edit">
      <%= link_to 'edit', edit_question_answer_path(@question, answer) %>
      <%= link_to 'delete', question_answer_path(@question, answer), :method => :delete %>
    </div>
      <h3><%= answer.content %></h3>
    <div class="answer-comment">
      <%= link_to 'comment', new_answer_comment_path(answer) %>
      <div class="voting-controls">
        <%= render :partial => 'votes/votes_answers', :locals => {:answer => answer} %>
      </div>
    </div>
<!-- CR make sure you are using includes in your controller to avoid hitting the database fore each comment -->
    <% answer.comments.each do |comment| %>
      <div class="question-comments-box">
        <h3><%= comment.body %></h3>
      </div>
    <% end %>

  </div>
<% end %>

app/views/questions/_question_comments.html.erb
<div class="question-content">
  <div class="delete-edit">
    <%= link_to 'edit', edit_question_path(@question) %>
    <%= link_to 'delete', question_path(@question), :method => :delete %>
  </div>

  <h1 class="content-header"><%= @question.title %></h1>
  <h3><%= @question.content %></h3>
  <div class="answer-comment">
    <%= link_to 'respond', new_question_answer_path(@question) %>
    <%= link_to 'comment', new_question_comment_path(@question) %>
    <div class="voting-controls">
      <%= render :partial => 'votes/votes_questions', :locals => {:question => @question} %>
    </div>
  </div>

  <% @question.comments.each do |comment| %>
    <div class="question-comments-box">
      <h3><%= comment.body %></h3>
    </div>
  <% end %>
</div>

app/views/questions/_questions.html.erb
<div class="question-container">
  <ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question)  %></li>
  <% end %>
  </ul>
</div>

app/views/questions/edit.html.erb
<h1 class="page-header">Edit: <%= @question.title %></h1>
<%= form_for @question do |f|%>
  <%= f.text_field :title %>
  <%= f.text_area :content, rows: 25, cols: 47 %>
  <%= f.submit 'submit', id: 'submit' %>
<% end %>

app/views/questions/index.html.erb
<h1 class="page-header">Query List</h1>

<div class="ask-button">
  <%= link_to 'ask a boot', new_question_path %>
</div>

<%= render 'questions' %>

app/views/questions/new.html.erb
<h1 class="page-header">Create Questions</h1>
<%= form_for @question do |f|%>
  <%= f.text_field :title, :placeholder => 'topic' %>
  <%= f.text_area :content, :placeholder => 'Ask your question...', rows: 25, cols: 47 %>
  <%= f.submit 'submit', id: 'submit' %>
<% end %>

app/views/questions/show.html.erb
<%= render 'questions/question_comments' %>

<h1 class="page-header" id="responses">Reponses</h1>

<%= render 'questions/answer_comments' %>

app/views/users/index.html.erb
<h1 class="page-header">Dev Overflow</h1>

<div class="stats">
  <!-- CR clean up your controller using includes to be able to remove the inject logic here and just use answer.count -->
<h2>Questions: <span><%= @questions.length %></span></h2>
<h2>Answers: <span><%= @answer.inject(:+) %></span></h2>
<h2>Comments: <span><%= @comments.inject(:+) %></span></h2>
<h2>Points: <span></span></h2>
</div>

app/views/users/new.html.erb
<h1 class="page-header">Create an Account</h1>

<ul>
<%= form_for @user do |f| %>
    <%= f.text_field :username, placeholder: 'username' %>
    <%= f.text_field :email, placeholder: 'email' %>
    <%= f.text_field :cohort, placeholder: 'cohort' %>
    <%= f.password_field :password, placeholder: 'password' %>
     <%= f.password_field :password_confirmation, placeholder: 'password_confirmation'%>
    <%= f.submit 'Create an Account', id: 'submit' %>
<% end %>
</ul>

app/views/votes/_votes_answers.html.erb
<%= link_to '+', answer_votes_path(answer), :method => :post, remote: true, :class => "upvote" %>
<span class="vote-count"><%= answer.votes.length %></span>
<% if answer.votes.length > 0 %>
  <%= link_to '-', answer_vote_path(answer, answer.votes.last), :method => :delete, remote: true, :class => "downvote" %>
<% end %>

app/views/votes/_votes_questions.html.erb
<!-- CR send the path in locals then you can use one partial for answervotes and comment votes -->

<%= link_to '+', question_votes_path(@question), :method => :post, remote: true, :class => "upvote" %>
<span class="vote-count"><%= @question.votes.length %></span>
<% if @question.votes.length > 0 %>
  <%= link_to '-', question_vote_path(@question, @question.votes.last), :method => :delete, remote: true, :class => "downvote" %>
<% end %>